### ISSUE TITLE
Custom filed separator/delimiter 

### ISSUE THREAD

**Issue by some-git-user** [siamahnaf/react-export-table#3]
I could't find an option for providing an custom filed separator/delimiter for the ```ExportAsCsv``` function.
In some fields I have comma separated data values. This leads to an problem while opening/parsing the exported csv file, because the standard string separator is also an comma:
```js
const headers = Object.keys(data[0]).join(',') + '\n'; // hard coded string separator
const rows = data.map(item => Object.values(item).join(',') + '\n'); // hard coded string separator
```

**Comment by siamahnaf** [comment]
Can you please give more details to reproduce?
