### ISSUE TITLE
ExportAsExcel seems to lowercase letters when using fileName

### ISSUE THREAD

**Issue by chrtmnn** [siamahnaf/react-export-table#4]
ExportAsExcel seems to lowercase the letters of any file name given using the fileName property. In ExportAsCsv it works perfectly.

https://github.com/siamahnaf/react-export-table/blob/8c8e5724977f5ff7ef43fb6f7a61e444609be835/dist/cjs/components/ExportAsExcel.js#L53

**Comment by siamahnaf** [comment]
Filename should lowercase always.
