### ISSUE TITLE
Possibility to rotate paper in print and pdf

### ISSUE THREAD

**Issue by gepless** [siamahnaf/react-export-table#8]
It would be great to be able to export to landscape format.

**Comment by siamahnaf** [comment]
I am little bit busy. But I will try it in 3-4 days.

**Comment by siamahnaf** [comment]
@gepless, Hello. You can use `orientation` props for exporting landscape format. I release version `3.1.7` with these new options. Let me know if you face further issues.

**Comment by gepless** [comment]
Nice, only issue I see is now is a TypeScript error but it works.

**Comment by siamahnaf** [comment]
Can you share me the TypeScript Error you are facing?

**Comment by gepless** [comment]
It was a non related issue :) so it works perfectly now.
